name: PSR-12 coding standard, Test, Coverage
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  coding-standard:
    name: PSR-12 coding standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install PHP code sniffer
        run: composer global require squizlabs/php_codesniffer

      - name: Check against PSR12 standard
        run: |
          `composer global config bin-dir --absolute --quiet`/phpcs --standard=PSR12 ./src


  tests:
    needs: coding-standard
    name: PHP [${{ matrix.php }}] With Lumen [${{ matrix.lumen }}]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1, 8.2 ]
        lumen: [ 6, 7, 8, 9, 10 ]
        exclude:
          - php: 8.0
            lumen: 6
          - php: 8.1
            lumen: 6
          - php: 8.2
            lumen: 6

          - php: 8.0
            lumen: 7
          - php: 8.1
            lumen: 7
          - php: 8.2
            lumen: 7

          - php: 7.2
            lumen: 8

          - php: 7.2
            lumen: 9
          - php: 7.3
            lumen: 9
          - php: 7.4
            lumen: 9

          - php: 7.2
            lumen: 10
          - php: 7.3
            lumen: 10
          - php: 7.4
            lumen: 10
          - php: 8.0
            lumen: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer require laravel/lumen:^${{ matrix.lumen }} --no-interaction --prefer-dist

      - name: Run test suite
        run: ./vendor/bin/phpunit --testdox --verbose

  coverage:
    needs: tests
    if: github.ref != 'refs/heads/dev'
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          php-version: 8.2

      - name: Install dependencies
        run: composer require laravel/lumen:"^9" --no-interaction --prefer-dist

      - name: Run tests for coverage
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Push to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
